# Generated by Django 5.1.5 on 2025-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='emoji',
            field=models.CharField(default='🐰', max_length=10),
        ),
    ]
