name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # 15분마다 실행

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to keep backend awake
        run: curl -s https://minsun24-github-io.onrender.com/guestbook/
